#!/usr/bin/env python3
"""Share one EpdUnicodeInterval table across the four UI font faces (v348).

WHY
---
The UI faces ubuntu_10/14 x regular/bold are generated by fontconvert.py from the
same charset, so every face header carries an identical copy of the interval table
(4,528 entries x 12 bytes = 54,336 bytes when this was written). Keeping one runtime
copy saves three of them -- 163,008 bytes of flash -- with no change in behaviour or
speed: the four EpdFontData structs simply point at the same array.

WHAT IT DOES
------------
1. Reads the interval table out of each face header and refuses to go on unless all
   four are byte-for-byte identical and internally consistent (sorted, contiguous
   glyph offsets, covering exactly that face's glyph array).
2. Writes lib/EpdFont/builtinFonts/ubuntu_ui_intervals.h: the one runtime copy plus
   a constexpr comparison helper.
3. Rewrites each face header:
     - its own table becomes `static constexpr` -- only a static_assert reads it, so
       nothing references it at run time and it is not emitted;
     - the static_assert compares it entry by entry with the shared copy;
     - its EpdFontData points at the shared copy.

So if a face is ever regenerated from a different charset, the build stops at the
static_assert instead of drawing the wrong glyphs on the device.

WHEN TO RUN
-----------
After regenerating any UI face: fontconvert.py writes a plain header that carries its
own table again (that header still builds -- it is just 54 KB bigger). Idempotent.

Usage: python3 scripts/share_ui_intervals.py
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FONT_DIR = ROOT / "lib" / "EpdFont" / "builtinFonts"
FACES = ["ubuntu_10_regular", "ubuntu_10_bold", "ubuntu_14_regular", "ubuntu_14_bold"]
SHARED_HEADER = "ubuntu_ui_intervals.h"
SHARED_NAME = "ubuntu_ui_sharedIntervals"
EQUAL_FN = "ubuntuUiIntervalsEqual"
INTERVAL_BYTES = 12  # sizeof(EpdUnicodeInterval): three uint32_t

ARRAY_RE = re.compile(
    r"^static (const|constexpr) EpdUnicodeInterval (\w+)Intervals\[\] = \{\n(.*?)\n\};\n", re.M | re.S
)
ENTRY_RE = re.compile(r"^    \{ 0x([0-9A-Fa-f]+), 0x([0-9A-Fa-f]+), 0x([0-9A-Fa-f]+) \},$")
GLYPHS_RE = re.compile(r"^static const EpdGlyph (\w+)Glyphs\[\] = \{\n(.*?)\n\};\n", re.M | re.S)

CONSTEXPR_NOTE = (
    "// CrossMosa v348：執行期用的是四個 UI 字面共用的那一份（ubuntu_ui_intervals.h）。\n"
    "// 這一份只給下面的 static_assert 在編譯期比對，沒有任何執行期引用，不會進 binary。\n"
)
SHARED_INCLUDE = f'#include "{SHARED_HEADER}"\n'


def fail(msg):
    sys.exit(f"share_ui_intervals: {msg}")


def parse_entries(face, body):
    entries = []
    for n, line in enumerate(body.split("\n"), 1):
        m = ENTRY_RE.match(line)
        if not m:
            fail(f"{face}: interval line {n} is not in fontconvert's format: {line!r}")
        entries.append(tuple(int(g, 16) for g in m.groups()))
    return entries


def check_consistent(face, entries, glyph_count):
    expected_offset = 0
    prev_last = -1
    for i, (first, last, offset) in enumerate(entries):
        if first > last or first <= prev_last:
            fail(f"{face}: interval {i} is empty, unsorted or overlapping")
        if offset != expected_offset:
            fail(f"{face}: interval {i} offset {offset} != expected {expected_offset}")
        expected_offset += last - first + 1
        prev_last = last
    if expected_offset != glyph_count:
        fail(f"{face}: intervals cover {expected_offset} glyphs but the glyph array has {glyph_count}")


def read_face(face):
    path = FONT_DIR / f"{face}.h"
    text = path.read_text(encoding="utf-8")
    arrays = list(ARRAY_RE.finditer(text))
    if len(arrays) != 1 or arrays[0].group(2) != face:
        fail(f"{path.name}: expected exactly one {face}Intervals[] table")
    glyphs = GLYPHS_RE.search(text)
    if not glyphs or glyphs.group(1) != face:
        fail(f"{path.name}: expected a {face}Glyphs[] table")
    glyph_count = sum(1 for line in glyphs.group(2).split("\n") if line.startswith("    {"))
    body = arrays[0].group(3)
    entries = parse_entries(face, body)
    check_consistent(face, entries, glyph_count)
    return path, text, arrays[0], body, entries


def rewrite_face(face, path, text, array_match):
    changed = False
    # 1. The face's own table: compile-time only.
    if array_match.group(1) == "const":
        old_decl = f"static const EpdUnicodeInterval {face}Intervals[] = {{\n"
        new_decl = CONSTEXPR_NOTE + f"static constexpr EpdUnicodeInterval {face}Intervals[] = {{\n"
        if text.count(old_decl) != 1:
            fail(f"{path.name}: declaration of {face}Intervals not found exactly once")
        text = text.replace(old_decl, new_decl)
        changed = True
    # 2. Include the shared copy and compare against it, right after the face's table.
    if SHARED_INCLUDE not in text:
        m = ARRAY_RE.search(text)
        guard = (
            SHARED_INCLUDE
            + f"static_assert({EQUAL_FN}({face}Intervals, {SHARED_NAME}),\n"
            + f'              "{face}: 碼位區間表跟共用的那份不一樣 —— 重製 UI 字型後要重跑 scripts/share_ui_intervals.py");\n'
        )
        text = text[: m.end()] + guard + text[m.end() :]
        changed = True
    # 3. EpdFontData points at the shared copy.
    old_ref = f"    {face}Intervals,\n"
    new_ref = f"    {SHARED_NAME},  // CrossMosa v348：四個 UI 字面共用（{SHARED_HEADER}）\n"
    if old_ref in text:
        if text.count(old_ref) != 1:
            fail(f"{path.name}: EpdFontData reference to {face}Intervals not found exactly once")
        text = text.replace(old_ref, new_ref)
        changed = True
    elif new_ref not in text:
        fail(f"{path.name}: EpdFontData does not reference {face}Intervals or {SHARED_NAME}")
    if changed:
        path.write_text(text, encoding="utf-8")
    return changed


def write_shared(body, count):
    saved = (len(FACES) - 1) * count * INTERVAL_BYTES
    content = (
        "/**\n"
        " * CrossMosa v348：四個 UI 字面（ubuntu_10／14 × regular／bold）共用的碼位區間表。\n"
        " * 由 scripts/share_ui_intervals.py 產生 —— 它先確認四個字型標頭檔裡的區間表逐位元組相同才寫這個檔。\n"
        " * 不要手改。重製任何一個 UI 字面之後重跑那支腳本（fontconvert.py 產出的標頭檔又會自帶一份）。\n"
        f" * 省下 {len(FACES) - 1} 份 × {count} 筆 × {INTERVAL_BYTES} bytes = {saved:,} bytes flash；\n"
        " * 執行期行為與速度不變（四個 EpdFontData 指向同一個陣列）。\n"
        " */\n"
        "#pragma once\n"
        "#include <cstddef>\n"
        "\n"
        '#include "EpdFontData.h"\n'
        "\n"
        f"static constexpr EpdUnicodeInterval {SHARED_NAME}[] = {{\n"
        f"{body}\n"
        "};\n"
        "\n"
        "// 各字面標頭檔用它在編譯期比對自己那份與共用這份：逐筆相同才編得過。\n"
        "template <size_t N, size_t M>\n"
        f"constexpr bool {EQUAL_FN}(const EpdUnicodeInterval (&a)[N], const EpdUnicodeInterval (&b)[M]) {{\n"
        "  if (N != M) return false;\n"
        "  for (size_t i = 0; i < N; i++) {\n"
        "    if (a[i].first != b[i].first || a[i].last != b[i].last || a[i].offset != b[i].offset) return false;\n"
        "  }\n"
        "  return true;\n"
        "}\n"
    )
    path = FONT_DIR / SHARED_HEADER
    old = path.read_text(encoding="utf-8") if path.exists() else None
    if old != content:
        path.write_text(content, encoding="utf-8")
    return saved, old != content


def main():
    faces = [read_face(face) for face in FACES]
    bodies = {body for _, _, _, body, _ in faces}
    if len(bodies) != 1:
        fail(
            "the four interval tables differ -- the faces were generated from different charsets. "
            "Regenerate them from the same charset first; not sharing."
        )
    body = faces[0][3]
    count = len(faces[0][4])
    saved, shared_changed = write_shared(body, count)
    print(f"{SHARED_HEADER}: {count} intervals ({'written' if shared_changed else 'unchanged'})")
    for face, (path, text, array_match, _, _) in zip(FACES, faces):
        changed = rewrite_face(face, path, text, array_match)
        print(f"{path.name}: {'rewritten' if changed else 'already shared'}")
    print(f"flash saved: {saved:,} bytes")


if __name__ == "__main__":
    main()
